export enum Action {
  // Posts
  VIEW_POST = 'VIEW_POST',
  CREATE_POST = 'CREATE_POST',
  EDIT_POST = 'EDIT_POST',
  DELETE_POST = 'DELETE_POST',

  // Feed
  VIEW_FEED = 'VIEW_FEED',
  VIEW_EXPLORE = 'VIEW_EXPLORE',

  // Social
  FOLLOW = 'FOLLOW',
  UNFOLLOW = 'UNFOLLOW',
  LIKE = 'LIKE',
  UNLIKE = 'UNLIKE',

  // Replies
  CREATE_REPLY = 'CREATE_REPLY',
  VIEW_REPLIES = 'VIEW_REPLIES',

  // Reports
  CREATE_REPORT = 'CREATE_REPORT',
  REVIEW_REPORTS = 'REVIEW_REPORTS',

  // Admin
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_MODERATION_LOGS = 'VIEW_MODERATION_LOGS',
}
